services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # Web interface
      - "7687:7687"  # Bolt protocol
    environment:
      NEO4J_AUTH: neo4j/password  # Change this for security
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_memory_pagecache_size: 512m
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf
      - neo4j_import:/var/lib/neo4j/import
    networks:
      - neo4j_network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_import:

networks:
  neo4j_network:
